Solari Cifra 5 Firmware: clock_task.c File Reference
clock_task.c File Reference
Mechanical clock synchronization and minute ticking task.
#include "rtos_init.h"
#include "rtc_helpers.h"
#include "clock_task.h"
Functions
static void prepareServo (void)
Initialize servo PWM and move to release (neutral) position.
static void clockAdvHour (void)
Advance the mechanical hour flap by one position using the servo.
static void shutdownServo (void)
Move servo to parking position and stop PWM output.
static void clockAdvMinute (const uint8_t slow)
Advance the mechanical minute flap by one position using the coil.
static void searchForZeroPosition (void)
Find the mechanical 00:00 position using physical sensors.
static void syncHours (uint8_t targetHours)
Advance the hour flap to match the target RTC hour.
static void syncMinutes (uint8_t targetMinutes)
Advance the minute flap to match the target RTC minutes.
static void advanceToHourBoundary (void)
Advance minutes from current position to the next hour boundary (XX:00).
void clockTask (void *parameters)
FreeRTOS task: mechanical clock synchronization and minute ticking.
Detailed Description
Mechanical clock synchronization and minute ticking task.
Version
2.0
Date
12/02/2026
Author
Alfredo Cortellini
Copyright
Copyright (c) 2026 Alfredo Cortellini. Licensed under CC BY-NC-SA 4.0. See https://creativecommons.org/licenses/by-nc-sa/4.0/
Definition in file clock_task.c.
Function Documentation
prepareServo()
void prepareServo (void) static
Initialize servo PWM and move to release (neutral) position.
    Starts with CCR4=0 (servo off), enables PWM on TIM_CHANNEL_4,
    waits 200ms for the servo to power up, then sets the release
    position and waits for it to settle.
    The servo controls the hour flap advancement mechanism:
    - PARKING: arm retracted (off position)
    - RELEASE: arm at neutral (ready to engage)
    - ENGAGE:  arm pushes the flap forward by one step
    HAL_TIM_PWM_Start(htim, channel): starts PWM output on the
    specified timer channel. The duty cycle is set via CCR4 register.
    vTaskDelay(ticks): suspends the calling task for the specified
    number of ticks, yielding the CPU to other tasks. Unlike a busy
    wait, the task consumes no CPU time while delayed.
Definition at line 39 of file clock_task.c.
References htimHandle, SERVO_PARK_TIME, and SERVO_RELEASE_PWM.
Referenced by searchForZeroPosition(), and syncHours().
clockAdvHour()
void clockAdvHour (void) static
Advance the mechanical hour flap by one position using the servo.
    Performs one engage→release cycle: pushes the servo arm to the
    engage position (SERVO_ENGAGE_PWM) to flip one hour flap, then
    returns to the release position. Updates the mechanical hour
    counter in backup registers via incrementMechHour().
    The servo must be initialized with prepareServo() before calling.
    After all hour advances are done, call shutdownServo() to park.
    Guarded by CIFRA5_DEBUG: when defined, skips the physical servo
    movement but still updates the backup register (for testing).
Definition at line 63 of file clock_task.c.
References htimHandle, incrementMechHour(), SERVO_ENGAGE_PWM, SERVO_ENGAGE_TIME, and SERVO_RELEASE_PWM.
Referenced by searchForZeroPosition(), and syncHours().
shutdownServo()
void shutdownServo (void) static
Move servo to parking position and stop PWM output.
    Moves the servo arm to SERVO_PARKING_PWM (fully retracted),
    waits for it to settle, then sets CCR4=0 and stops the PWM
    timer to eliminate idle current draw from the servo.
    HAL_TIM_PWM_Stop(htim, channel): stops PWM generation on the
    timer channel. The output pin goes to its idle level.
Definition at line 87 of file clock_task.c.
References htimHandle, SERVO_PARK_TIME, and SERVO_PARKING_PWM.
Referenced by searchForZeroPosition(), and syncHours().
clockAdvMinute()
void clockAdvMinute (const uint8_t slow) static
Advance the mechanical minute flap by one position using the coil.
    The minute mechanism uses an electromagnetic coil that alternates
    between two pins (tick/tock) on each advance. The alternation state
    is tracked in backup register DR2 bit 0 via getLastTick/setLastTick.
    Each pulse: drive the coil pin LOW (excite), wait coilExcite ms,
    then drive HIGH (release), wait coilRest ms. The slow parameter
    adds COIL_EXTRA_TIME to both durations for gentler movement during
    normal operation (vs. fast sync).
    After the pulse, updates the mechanical minute counter via
    incrementMechMinute() and saves the new tick state.
    HAL_GPIO_WritePin(port, pin, state): directly sets/clears a GPIO
    pin. GPIO_PIN_RESET=0 (coil energized), GPIO_PIN_SET=1 (coil off).
    Guarded by CIFRA5_DEBUG: when defined, skips physical GPIO
    toggling but still updates backup registers.
Parameters
slow 0 = fast (sync mode), 1 = slow (normal tick with extra delay)
Definition at line 118 of file clock_task.c.
References CLK_TICK_GPIO_Port, CLK_TICK_Pin, CLK_TOCK_GPIO_Port, CLK_TOCK_Pin, COIL_EXCITE_TIME, COIL_EXTRA_TIME, COIL_REST_TIME, getLastTick(), incrementMechMinute(), and setLastTick().
Referenced by advanceToHourBoundary(), clockTask(), searchForZeroPosition(), and syncMinutes().
searchForZeroPosition()
void searchForZeroPosition (void) static
Find the mechanical 00:00 position using physical sensors.
    Called on first sync when the mechanical position is unknown (both
    mech hours and minutes are 0 in backup registers = not yet calibrated).
    Phase 1 — Find 00 minutes:
    Advances the minute flap until the hour sensor detects a 0→1
    transition (falling edge = magnet leaving sensor). This indicates
    the minutes have crossed an hour boundary (XX:00).
    Error after 62 attempts (> 60 minutes = sensor missing).
    Phase 2 — Find 00 hours:
    Activates the servo, then advances the hour flap until the day
    sensor detects a 1→0 transition (rising edge = 24→00 rollover).
    Error after 25 attempts (> 24 hours = sensor missing).
    On error, notifies displayTask with an error event and suspends.
    The task remains suspended until the user power-cycles the device.
    vTaskSuspend(NULL): suspends the calling task indefinitely.
    The task will not run again until another task calls
    vTaskResume(handle) on it. Passing NULL means "suspend myself".
Definition at line 173 of file clock_task.c.
References clockAdvHour(), clockAdvMinute(), DISP_EV_ERR_SNS_DAY, DISP_EV_ERR_SNS_HOUR, DISP_EV_SYN_SRC_DAY, DISP_EV_SYN_SRC_HOUR, displayTaskHandle, prepareServo(), resetMechPosition(), shutdownServo(), SNS_DAY_GPIO_Port, SNS_DAY_Pin, SNS_HOUR_GPIO_Port, and SNS_HOUR_Pin.
Referenced by clockTask().
syncHours()
void syncHours (uint8_t targetHours) static
Advance the hour flap to match the target RTC hour.
    If the servo is not already at release position, calls
    prepareServo() first (prevents double-initialization). Then
    loops clockAdvHour() until the mechanical hours (from backup
    registers) match targetHours. Finally parks the servo.
    Since hours wrap around 0-23, this handles any direction
    (e.g. mechanical=22, target=3 → advances 5 times through 0).
Parameters
targetHours Desired hour position (0-23, from RTC)
Definition at line 225 of file clock_task.c.
References clockAdvHour(), DISP_EV_SYN_SET_HOUR, displayTaskHandle, getMechHours(), htimHandle, prepareServo(), SERVO_RELEASE_PWM, and shutdownServo().
Referenced by clockTask().
syncMinutes()
void syncMinutes (uint8_t targetMinutes) static
Advance the minute flap to match the target RTC minutes.
    Assumes the mechanical clock is at XX:00 (either from sensor
    search or advanceToHourBoundary). Advances targetMinutes times
    using fast coil pulses (slow=0).
Parameters
targetMinutes Number of minute steps to advance (0-59, from RTC)
Definition at line 249 of file clock_task.c.
References clockAdvMinute(), DISP_EV_SYN_SET_MIN, and displayTaskHandle.
Referenced by clockTask().
advanceToHourBoundary()
void advanceToHourBoundary (void) static
Advance minutes from current position to the next hour boundary (XX:00).
    Used in "fast sync" when the mechanical position is known from
    backup registers (not 00:00). If minutes are already at 0, does
    nothing. Otherwise advances (60 - currentMinutes) times to reach
    the next hour, which also increments the mechanical hour.
    After this function, the mechanical clock is at (H+1):00 and
    syncHours/syncMinutes can set the exact target.
Definition at line 270 of file clock_task.c.
References clockAdvMinute(), DISP_EV_SYN_SRC_HOUR, displayTaskHandle, and getMechMinutes().
Referenced by clockTask().
clockTask()
void clockTask (void * parameters)
FreeRTOS task: mechanical clock synchronization and minute ticking.
    Manages the physical Solari Cifra 5 flip clock mechanism. Runs in
    three phases inside an outer while(1) loop:
    PHASE 1 — PRE-SYNC:
    On first boot (rtcInitOk=0, RTC never initialized), sends
    DISP_EV_FORCE_SETUP to trigger the setup wizard and blocks on
    xTaskNotifyWait until the user finishes setting the time.
    Then waits out any active silent period (checks every 60s).
    PHASE 2 — SYNC:
    Suspends buttonTask to prevent user interaction during sync.
    If mechanical position is 00:00 (unknown), runs sensor-based
    searchForZeroPosition(). Otherwise does a fast sync via
    advanceToHourBoundary(). Then reads RTC time and calls
    syncHours() + syncMinutes() to match the mechanical clock.
    Notifies displayTask with DISP_EV_SYN_END when complete.
    PHASE 3 — NORMAL OPERATION:
    Polls every CLOCK_UPDATE_INTERVAL (100ms). Compares mechanical
    minutes (from backup registers) to RTC minutes. When they differ,
    advances one minute flap using clockAdvMinute(slow=1).
    Monitors the hour sensor during advances — an unexpected hour
    transition indicates mechanical drift and triggers a full resync
    (breaks back to Phase 2).
    Also handles silent period entry/exit (exit triggers resync).
    xTaskNotifyWait(clearEntry, clearExit, &value, timeout): blocks
    until a notification arrives or timeout. In Phase 1, uses
    portMAX_DELAY (infinite wait). In Phase 3, uses 100ms timeout
    for periodic polling.
    vTaskSuspend(handle): suspends another task. Used to disable
    buttonTask during sync. vTaskSuspend on an already-suspended
    task is a safe no-op.
Parameters
parameters Cast to uint8_t: 0 = RTC not initialized (first boot), non-zero = RTC valid (normal boot / power cycle)
Definition at line 322 of file clock_task.c.
References advanceToHourBoundary(), buttonTaskHandle, CLOCK_EV_NEW_TIME, CLOCK_UPDATE_INTERVAL, clockAdvMinute(), DISP_EV_ERR_MANY_SYNC, DISP_EV_FORCE_SETUP, DISP_EV_SYN_END, DISP_EV_SYN_START, displayTaskHandle, getMechHours(), getMechMinutes(), hrtcHandle, isInSilentPeriod(), resetMechPosition(), RTC_Date, RTC_Time, searchForZeroPosition(), SNS_HOUR_GPIO_Port, SNS_HOUR_Pin, syncHours(), and syncMinutes().
Referenced by createRTOS_Tasks().