Solari Cifra 5 Firmware: clock_task.h File Reference
clock_task.h File Reference
Mechanical clock synchronization and minute ticking task.
#include "rtos_init.h"
Macros
#define SERVO_PARKING_PWM 61
#define SERVO_RELEASE_PWM 74
#define SERVO_ENGAGE_PWM 81
#define SERVO_ENGAGE_TIME 300
#define SERVO_PARK_TIME 500
#define COIL_REST_TIME 200
#define COIL_EXCITE_TIME 200
#define COIL_EXTRA_TIME 0
#define CLOCK_UPDATE_INTERVAL 100
Functions
void clockTask (void *parameters)
FreeRTOS task: mechanical clock synchronization and minute ticking.
Detailed Description
Mechanical clock synchronization and minute ticking task.
Version
2.0
Date
12/02/2026
Author
Alfredo Cortellini
Copyright
Copyright (c) 2026 Alfredo Cortellini. Licensed under CC BY-NC-SA 4.0. See https://creativecommons.org/licenses/by-nc-sa/4.0/
Definition in file clock_task.h.
Macro Definition Documentation
SERVO_PARKING_PWM
#define SERVO_PARKING_PWM 61
Definition at line 26 of file clock_task.h.
Referenced by shutdownServo().
SERVO_RELEASE_PWM
#define SERVO_RELEASE_PWM 74
Definition at line 27 of file clock_task.h.
Referenced by clockAdvHour(), prepareServo(), and syncHours().
SERVO_ENGAGE_PWM
#define SERVO_ENGAGE_PWM 81
Definition at line 28 of file clock_task.h.
Referenced by clockAdvHour().
SERVO_ENGAGE_TIME
#define SERVO_ENGAGE_TIME 300
Definition at line 29 of file clock_task.h.
Referenced by clockAdvHour().
SERVO_PARK_TIME
#define SERVO_PARK_TIME 500
Definition at line 30 of file clock_task.h.
Referenced by prepareServo(), and shutdownServo().
COIL_REST_TIME
#define COIL_REST_TIME 200
Definition at line 33 of file clock_task.h.
Referenced by clockAdvMinute().
COIL_EXCITE_TIME
#define COIL_EXCITE_TIME 200
Definition at line 34 of file clock_task.h.
Referenced by clockAdvMinute().
COIL_EXTRA_TIME
#define COIL_EXTRA_TIME 0
Definition at line 35 of file clock_task.h.
Referenced by clockAdvMinute().
CLOCK_UPDATE_INTERVAL
#define CLOCK_UPDATE_INTERVAL 100
Definition at line 38 of file clock_task.h.
Referenced by clockTask().
Function Documentation
clockTask()
void clockTask (void * parameters)
FreeRTOS task: mechanical clock synchronization and minute ticking.
    Manages the physical Solari Cifra 5 flip clock mechanism. Runs in
    three phases inside an outer while(1) loop:
    PHASE 1 — PRE-SYNC:
    On first boot (rtcInitOk=0, RTC never initialized), sends
    DISP_EV_FORCE_SETUP to trigger the setup wizard and blocks on
    xTaskNotifyWait until the user finishes setting the time.
    Then waits out any active silent period (checks every 60s).
    PHASE 2 — SYNC:
    Suspends buttonTask to prevent user interaction during sync.
    If mechanical position is 00:00 (unknown), runs sensor-based
    searchForZeroPosition(). Otherwise does a fast sync via
    advanceToHourBoundary(). Then reads RTC time and calls
    syncHours() + syncMinutes() to match the mechanical clock.
    Notifies displayTask with DISP_EV_SYN_END when complete.
    PHASE 3 — NORMAL OPERATION:
    Polls every CLOCK_UPDATE_INTERVAL (100ms). Compares mechanical
    minutes (from backup registers) to RTC minutes. When they differ,
    advances one minute flap using clockAdvMinute(slow=1).
    Monitors the hour sensor during advances — an unexpected hour
    transition indicates mechanical drift and triggers a full resync
    (breaks back to Phase 2).
    Also handles silent period entry/exit (exit triggers resync).
    xTaskNotifyWait(clearEntry, clearExit, &value, timeout): blocks
    until a notification arrives or timeout. In Phase 1, uses
    portMAX_DELAY (infinite wait). In Phase 3, uses 100ms timeout
    for periodic polling.
    vTaskSuspend(handle): suspends another task. Used to disable
    buttonTask during sync. vTaskSuspend on an already-suspended
    task is a safe no-op.
Parameters
parameters Cast to uint8_t: 0 = RTC not initialized (first boot), non-zero = RTC valid (normal boot / power cycle)
Definition at line 322 of file clock_task.c.
References advanceToHourBoundary(), buttonTaskHandle, CLOCK_EV_NEW_TIME, CLOCK_UPDATE_INTERVAL, clockAdvMinute(), DISP_EV_ERR_MANY_SYNC, DISP_EV_FORCE_SETUP, DISP_EV_SYN_END, DISP_EV_SYN_START, displayTaskHandle, getMechHours(), getMechMinutes(), hrtcHandle, isInSilentPeriod(), resetMechPosition(), RTC_Date, RTC_Time, searchForZeroPosition(), SNS_HOUR_GPIO_Port, SNS_HOUR_Pin, syncHours(), and syncMinutes().
Referenced by createRTOS_Tasks().