Solari Cifra 5 Firmware: display_task.c File Reference
display_task.c File Reference
OLED display controller and UI state machine task.
#include <string.h>
#include "rtos_init.h"
#include "rtc_helpers.h"
#include "display_task.h"
#include "ssd1306.h"
Functions
static void displayShowClock (uint8_t *time)
Render time as large digits on OLED: HH:MM with colon separator.
static void displayShowSilentHours (uint8_t *time)
Render silent hours on OLED: HH-HH with dash separator.
static void displayShowCalibration (uint8_t *time)
Render calibration value on OLED: ±NNN (sign + 3 digits).
static void displayUpdateTimeVar (uint8_t *time)
Split current RTC time into individual digit values.
static void displayCursorSetTime (uint8_t digit, const uint8_t symbol)
Draw or clear the cursor marker above a digit position.
static void displayMessage (uint8_t msgId, char *buffer)
Display a two-line informative message centered on the OLED.
static void displayTitle (uint8_t msgId, char *buffer)
Display a title string centered on the top row (page 0) of the OLED.
static void displayOnOff (uint8_t newState, displayCtx_t *ctx)
Turn the OLED display on or off, tracking state in the context.
static void enterSetRtc (displayCtx_t *ctx, char *buf)
Enter the RTC time-setting sub-menu (DISP_SET_RTC).
static void enterSetSilent (displayCtx_t *ctx, char *buf)
Enter the silent hours sub-menu (DISP_SET_SILENT).
static void enterSetCorrection (displayCtx_t *ctx, char *buf)
Enter the RTC calibration sub-menu (DISP_SET_CORRECTION).
static void handleClockBtns (uint32_t eventId, displayCtx_t *ctx, char *buf)
Handle button events while in DISP_CLOCK (idle) state.
static void handleSetRtcBtns (uint32_t eventId, displayCtx_t *ctx)
Handle button events in DISP_SET_RTC state (time digit editing).
static void handleSetSilentBtns (uint32_t eventId, displayCtx_t *ctx, char *buf)
Handle button events in DISP_SET_SILENT state (HH-HH editing).
static void handleSetCorrBtns (uint32_t eventId, displayCtx_t *ctx, char *buf)
Handle button events in DISP_SET_CORRECTION state (±NNN editing).
void displayTask (void *parameters)
FreeRTOS task: OLED display controller and UI state machine.
Variables
const char dispMsg [9][2][11]
const char dispTitle [6][11]
const uint8_t setTimeDigitPos [4]
Detailed Description
OLED display controller and UI state machine task.
Version
2.0
Date
12/02/2026
Author
Alfredo Cortellini
Copyright
Copyright (c) 2026 Alfredo Cortellini. Licensed under CC BY-NC-SA 4.0. See https://creativecommons.org/licenses/by-nc-sa/4.0/
Definition in file display_task.c.
Function Documentation
displayShowClock()
void displayShowClock (uint8_t * time) static
Render time as large digits on OLED: HH:MM with colon separator.
    Writes each digit at its fixed X position (DIGIT_*_X defines).
    Digit values are raw 0-9, converted to ASCII by adding 48.
Parameters
time Array of 4 digit values [tensHrs, unitsHrs, tensMins, unitsMins]
Definition at line 61 of file display_task.c.
References DIGIT_COLON_X, DIGIT_TEEN_HRS_X, DIGIT_TEEN_MINS_X, DIGIT_TIME_Y, DIGIT_UNIT_HRS_X, DIGIT_UNIT_MINS_X, DISP_FONT_L, ssd1306_SetCursor(), ssd1306_WriteChar(), TEEN_HRS, TEEN_MINS, UNIT_HRS, and UNIT_MINS.
Referenced by displayTask(), enterSetRtc(), and handleSetRtcBtns().
displayShowSilentHours()
void displayShowSilentHours (uint8_t * time) static
Render silent hours on OLED: HH-HH with dash separator.
    Same layout as displayShowClock but uses '-' (ASCII 45) instead
    of ':' in the center position.
Parameters
time Array of 4 digit values [tensStart, unitsStart, tensEnd, unitsEnd]
Definition at line 85 of file display_task.c.
References DIGIT_COLON_X, DIGIT_TEEN_HRS_X, DIGIT_TEEN_MINS_X, DIGIT_TIME_Y, DIGIT_UNIT_HRS_X, DIGIT_UNIT_MINS_X, DISP_FONT_L, ssd1306_SetCursor(), and ssd1306_WriteChar().
Referenced by enterSetSilent(), and handleSetSilentBtns().
displayShowCalibration()
void displayShowCalibration (uint8_t * time) static
Render calibration value on OLED: ±NNN (sign + 3 digits).
    Position 0 shows '+' (ASCII 43) or '-' (ASCII 45) based on
    time[0] (1=plus, 0=minus). The colon position shows a blank
    space. Digits 1-3 show the numeric value (0-511).
Parameters
time Array [plusFlag, hundreds, tens, units]
Definition at line 110 of file display_task.c.
References DIGIT_COLON_X, DIGIT_TEEN_HRS_X, DIGIT_TEEN_MINS_X, DIGIT_TIME_Y, DIGIT_UNIT_HRS_X, DIGIT_UNIT_MINS_X, DISP_FONT_L, ssd1306_SetCursor(), and ssd1306_WriteChar().
Referenced by enterSetCorrection(), and handleSetCorrBtns().
displayUpdateTimeVar()
void displayUpdateTimeVar (uint8_t * time) static
Split current RTC time into individual digit values.
    Reads from the global RTC_Time struct (which must have been
    populated by a prior HAL_RTC_GetTime call) and writes the four
    digit values into the provided array.
Parameters
[out] time Array of 4 digits [tensHrs, unitsHrs, tensMins, unitsMins]
Definition at line 136 of file display_task.c.
References RTC_Time, TEEN_HRS, TEEN_MINS, UNIT_HRS, and UNIT_MINS.
Referenced by displayTask(), and enterSetRtc().
displayCursorSetTime()
void displayCursorSetTime (uint8_t digit, const uint8_t symbol) static
Draw or clear the cursor marker above a digit position.
    Writes three small characters (symbol) above the digit to form
    a visual cursor. Use ASCII 96 (grave accent) to show the cursor, or
    ASCII 32 (' ') to erase it when moving to the next digit.
Parameters
digit Digit index (0-3), maps to X position via setTimeDigitPos[]
symbol ASCII character to draw (96 = show cursor, 32 = clear)
Definition at line 154 of file display_task.c.
References DIGIT_TIME_Y, DISP_FONT_S, setTimeDigitPos, ssd1306_SetCursor(), and ssd1306_WriteChar().
Referenced by enterSetCorrection(), enterSetRtc(), enterSetSilent(), handleSetCorrBtns(), handleSetRtcBtns(), and handleSetSilentBtns().
displayMessage()
void displayMessage (uint8_t msgId, char * buffer) static
Display a two-line informative message centered on the OLED.
    Messages are stored in the dispMsg[9][2][11] array, indexed by msgId.
    Each message has two rows of up to 10 characters. The function clears
    margin characters on both sides of each row to handle variable-width
    centering from previous messages.
    SSD1306_WIDTH and SSD1306_CHAR_WIDTH are display driver constants
    used to compute centered X positions.
Parameters
msgId Index into dispMsg[][] (0-8, derived from event subtraction)
buffer Caller-provided 11-byte char buffer used as scratch for strcpy
Definition at line 179 of file display_task.c.
References DISP_FONT_S, dispMsg, SSD1306_CHAR_WIDTH, ssd1306_SetCursor(), SSD1306_WIDTH, ssd1306_WriteChar(), and ssd1306_WriteString().
Referenced by displayTask().
displayTitle()
void displayTitle (uint8_t msgId, char * buffer) static
Display a title string centered on the top row (page 0) of the OLED.
    Titles are stored in the dispTitle[6][11] array, indexed by the
    current display state (dispStateEnum). All titles are 10 characters
    wide, so no margin clearing is needed (unlike displayMessage).
Parameters
msgId Index into dispTitle[] (typically ctx.state cast to uint8_t)
buffer Caller-provided 11-byte char buffer used as scratch for strcpy
Definition at line 215 of file display_task.c.
References DISP_FONT_S, dispTitle, SSD1306_CHAR_WIDTH, ssd1306_SetCursor(), SSD1306_WIDTH, and ssd1306_WriteString().
Referenced by displayTask(), enterSetCorrection(), enterSetRtc(), and enterSetSilent().
displayOnOff()
void displayOnOff (uint8_t newState, displayCtx_t * ctx) static
Turn the OLED display on or off, tracking state in the context.
    Only sends the hardware command (ssd1306_SetDisplayOnOff) when the
    requested state differs from the current state, avoiding redundant
    I2C traffic. When turning ON, resets the auto-off timer by updating
    ctx->lastOnTime with the current tick count.
    xTaskGetTickCount() returns the current RTOS tick count (a
    monotonically increasing counter incremented by the SysTick ISR,
    typically every 1 ms). Used here to timestamp the last display
    wake-up for auto-off timeout comparison.
Parameters
newState ON (1) or OFF (0), from onOffEnum
ctx Display context — reads/writes ctx->isOn, ctx->lastOnTime
Definition at line 239 of file display_task.c.
References displayCtx_t::isOn, displayCtx_t::lastOnTime, ON, and ssd1306_SetDisplayOnOff().
Referenced by displayTask().
enterSetRtc()
void enterSetRtc (displayCtx_t * ctx, char * buf) static
Enter the RTC time-setting sub-menu (DISP_SET_RTC).
    Shared entry point for both first-boot setup (end of wizard chain)
    and manual long-press-SET entry from DISP_CLOCK. Clears the screen,
    loads current RTC time into the digit array, displays the title and
    clock digits, and positions the cursor on the first digit (tens hours).
    Always clears ctx->setupMode to 0 because this is the LAST screen
    in the setup wizard chain (silent → calibration → time).
Parameters
ctx Display context — sets state, digitCursor, setupMode, showTime[]
buf Caller-provided 11-byte scratch buffer for displayTitle
Definition at line 264 of file display_task.c.
References displayCtx_t::digitCursor, DISP_SET_RTC, displayCursorSetTime(), displayShowClock(), displayTitle(), displayUpdateTimeVar(), displayCtx_t::setupMode, displayCtx_t::showTime, ssd1306_ClearScreen(), and displayCtx_t::state.
Referenced by handleClockBtns(), and handleSetCorrBtns().
enterSetSilent()
void enterSetSilent (displayCtx_t * ctx, char * buf) static
Enter the silent hours sub-menu (DISP_SET_SILENT).
    Loads current silent start/end hours from backup register DR3 into
    the digit array as [tensStart, unitsStart, tensEnd, unitsEnd].
    Clears the screen and renders the title, HH-HH display, and cursor.
    Entry paths:
    - First-boot wizard (DISP_EV_FORCE_SETUP → setupMode=1)
    - Manual: long-press INC from DISP_CLOCK
    Does NOT clear setupMode — the caller sets it before calling.
Parameters
ctx Display context — sets state, digitCursor, showTime[]
buf Caller-provided 11-byte scratch buffer for displayTitle
Definition at line 292 of file display_task.c.
References displayCtx_t::digitCursor, DISP_SET_SILENT, displayCursorSetTime(), displayShowSilentHours(), displayTitle(), getSilentEndHour(), getSilentStartHour(), displayCtx_t::showTime, ssd1306_ClearScreen(), and displayCtx_t::state.
Referenced by displayTask(), and handleClockBtns().
enterSetCorrection()
void enterSetCorrection (displayCtx_t * ctx, char * buf) static
Enter the RTC calibration sub-menu (DISP_SET_CORRECTION).
    Reads the current calibration from backup register DR4 and splits
    it into [plusFlag, hundreds, tens, units] in the digit array.
    Clears the screen and renders the title, ±NNN display, and cursor.
    Entry paths:
    - Setup wizard chain (from handleSetSilentBtns when setupMode=1)
    - Manual: long-press DEC from DISP_CLOCK
Parameters
ctx Display context — sets state, digitCursor, showTime[]
buf Caller-provided 11-byte scratch buffer for displayTitle
Definition at line 320 of file display_task.c.
References displayCtx_t::digitCursor, DISP_SET_CORRECTION, displayCursorSetTime(), displayShowCalibration(), displayTitle(), getCalibration(), displayCtx_t::showTime, ssd1306_ClearScreen(), and displayCtx_t::state.
Referenced by handleClockBtns(), and handleSetSilentBtns().
handleClockBtns()
void handleClockBtns (uint32_t eventId, displayCtx_t * ctx, char * buf) static
Handle button events while in DISP_CLOCK (idle) state.
    Only long presses trigger sub-menu transitions:
    - Long SET → DISP_SET_RTC (blocked if inside silent period)
    - Long INC → DISP_SET_SILENT (edit silent hours)
    - Long DEC → DISP_SET_CORRECTION (edit RTC calibration)
    Short presses are no-ops (display was already woken by caller).
Parameters
eventId Button event code (101-106)
ctx Display context — may transition state
buf 11-byte scratch buffer for display rendering
Definition at line 350 of file display_task.c.
References DISP_EV_BTN_DEC_LONG, DISP_EV_BTN_INC_LONG, DISP_EV_BTN_SET_LONG, enterSetCorrection(), enterSetRtc(), enterSetSilent(), and isInSilentPeriod().
Referenced by displayTask().
handleSetRtcBtns()
void handleSetRtcBtns (uint32_t eventId, displayCtx_t * ctx) static
Handle button events in DISP_SET_RTC state (time digit editing).
    SET button advances cursor to next digit (0→1→2→3→commit).
    INC/DEC buttons modify the digit at the current cursor position
    with validation: hours 00-23 (tens 0-2, units clamped to 0-3 when
    tens=2), minutes 00-59 (tens 0-5, units 0-9).
    When the cursor reaches position 4 (past the last digit):
    - Writes the entered time to the RTC via HAL_RTC_SetTime/SetDate
      inside a critical section (interrupts disabled to prevent
      partial RTC register writes)
    - Transitions to DISP_SYNC and notifies clockTask with
      CLOCK_EV_NEW_TIME to start mechanical synchronization
    xTaskNotify(handle, value, eSetValueWithOverwrite): sends a 32-bit
    notification value to the target task. eSetValueWithOverwrite means
    the value is written unconditionally (overwrites any pending
    unread notification).
Parameters
eventId Button event code (101-103 for short presses)
ctx Display context — reads/writes showTime[], digitCursor, state
Definition at line 392 of file display_task.c.
References CLOCK_EV_NEW_TIME, clockTaskHandle, displayCtx_t::digitCursor, DISP_EV_BTN_DEC, DISP_EV_BTN_INC, DISP_EV_BTN_SET, DISP_SYNC, displayCursorSetTime(), displayShowClock(), hrtcHandle, RTC_Date, RTC_Time, displayCtx_t::showTime, displayCtx_t::state, TEEN_HRS, TEEN_MINS, UNIT_HRS, and UNIT_MINS.
Referenced by displayTask().
handleSetSilentBtns()
void handleSetSilentBtns (uint32_t eventId, displayCtx_t * ctx, char * buf) static
Handle button events in DISP_SET_SILENT state (HH-HH editing).
    Edits two hour values (start and end of silent period) displayed
    as HH-HH. Same digit editing pattern as handleSetRtcBtns but
    both pairs are validated as hours (0-23).
    On commit (cursor reaches 4):
    - Saves start/end hours to backup register DR3 via setSilentHours()
    - Persists to Flash via flashWriteSettings()
    - If setupMode=1 (first-boot wizard): chains to enterSetCorrection()
    - If setupMode=0 (manual entry): returns to DISP_CLOCK
Parameters
eventId Button event code (101-103 for short presses)
ctx Display context — reads/writes showTime[], digitCursor, state
buf 11-byte scratch buffer for display rendering
Definition at line 469 of file display_task.c.
References displayCtx_t::digitCursor, DISP_CLOCK, DISP_EV_BTN_DEC, DISP_EV_BTN_INC, DISP_EV_BTN_SET, displayCursorSetTime(), displayShowSilentHours(), enterSetCorrection(), flashWriteSettings(), setSilentHours(), displayCtx_t::setupMode, displayCtx_t::showTime, ssd1306_ClearScreen(), and displayCtx_t::state.
Referenced by displayTask().
handleSetCorrBtns()
void handleSetCorrBtns (uint32_t eventId, displayCtx_t * ctx, char * buf) static
Handle button events in DISP_SET_CORRECTION state (±NNN editing).
    Edits the RTC smooth calibration value displayed as ±NNN (0-511).
    Digit 0 toggles the sign (+/-). Digits 1-3 edit the numeric value
    with clamping to ensure the total never exceeds 511.
    On commit (cursor reaches 4):
    - Saves to backup register DR4 via setCalibration()
    - Applies immediately to RTC hardware via applyCalibration()
    - Persists to Flash via flashWriteSettings()
    - If setupMode=1 (first-boot wizard): chains to enterSetRtc()
    - If setupMode=0 (manual entry): returns to DISP_CLOCK
Parameters
eventId Button event code (101-103 for short presses)
ctx Display context — reads/writes showTime[], digitCursor, state
buf 11-byte scratch buffer for display rendering
Definition at line 542 of file display_task.c.
References applyCalibration(), displayCtx_t::digitCursor, DISP_CLOCK, DISP_EV_BTN_DEC, DISP_EV_BTN_INC, DISP_EV_BTN_SET, displayCursorSetTime(), displayShowCalibration(), enterSetRtc(), flashWriteSettings(), setCalibration(), displayCtx_t::setupMode, displayCtx_t::showTime, ssd1306_ClearScreen(), and displayCtx_t::state.
Referenced by displayTask().
displayTask()
void displayTask (void * parameters)
FreeRTOS task: OLED display controller and UI state machine.
    This task owns the SSD1306 OLED display. It receives notifications
    from buttonTask (user input) and clockTask (sync progress/errors),
    and updates the display accordingly.
    State machine (ctx.state):
    - DISP_CLOCK:          Idle, shows current RTC time (HH:MM)
    - DISP_SET_RTC:        Digit-by-digit time editing
    - DISP_SET_SILENT:     Digit-by-digit silent hours editing (HH-HH)
    - DISP_SET_CORRECTION: Digit-by-digit calibration editing (±NNN)
    - DISP_SYNC:           Mechanical sync in progress (buttons disabled)
    - DISP_ERROR:          Error message displayed
    Event handling:
    - DISP_EV_FORCE_SETUP (999): First-boot wizard chain
    - Button events (101-106): Dispatched to per-state handlers
    - Sync events (201-206): Show sync progress messages
    - Error events (301-309): Show error messages
    - Timeout (no event): Refresh clock display + auto-off check
    Display wake logic: if display is OFF and any button is pressed,
    the display turns ON but the event is NOT forwarded to handlers
    (wake-only). This prevents accidental sub-menu entry.
    xTaskNotifyWait(clearOnEntry, clearOnExit, &value, timeout):
    blocks the task until a notification arrives or timeout expires.
    - clearOnEntry/Exit: bit masks to clear from the notification value
    - Returns pdTRUE if a notification was received, pdFALSE on timeout
    - Here: clears all bits on exit (0xffffffff) to consume the event
    vTaskResume(handle): resumes a suspended task. Used here to
    re-enable buttonTask after processing its event. Safe to call
    on an already-running task (no-op).
    pdMS_TO_TICKS(ms): converts milliseconds to RTOS tick count
    (depends on configTICK_RATE_HZ, typically 1000 = 1ms/tick).
Parameters
parameters Unused (NULL)
Definition at line 651 of file display_task.c.
References buttonTaskHandle, DISP_CLOCK, DISP_ERROR, DISP_EV_ERR_START, DISP_EV_FORCE_SETUP, DISP_EV_SYN_END, DISP_EV_SYN_START, DISP_SET_CORRECTION, DISP_SET_RTC, DISP_SET_SILENT, DISP_SYNC, DISPLAY_CLOCK_INTERVAL, DISPLAY_OFF_TIMEOUT, DISPLAY_TASK_DELAY, displayMessage(), displayOnOff(), displayShowClock(), displayTitle(), displayUpdateTimeVar(), enterSetSilent(), handleClockBtns(), handleSetCorrBtns(), handleSetRtcBtns(), handleSetSilentBtns(), displayCtx_t::isOn, displayCtx_t::lastClockUpdate, displayCtx_t::lastOnTime, OFF, ON, displayCtx_t::setupMode, displayCtx_t::showTime, ssd1306_ClearScreen(), displayCtx_t::state, and timeLapsed.
Referenced by createRTOS_Tasks().
Variable Documentation
dispMsg
const char dispMsg[9][2][11]
Initial value:
                   = {
        {DISP_MSG01_ROW01, DISP_MSG01_ROW02},
        {DISP_MSG02_ROW01, DISP_MSG02_ROW02},
        {DISP_MSG03_ROW01, DISP_MSG03_ROW02},
        {DISP_MSG04_ROW01, DISP_MSG04_ROW02},
        {DISP_MSG05_ROW01, DISP_MSG05_ROW02},
        {DISP_MSG06_ROW01, DISP_MSG06_ROW02},
        {DISP_MSG07_ROW01, DISP_MSG07_ROW02},
        {DISP_MSG08_ROW01, DISP_MSG08_ROW02},
        {DISP_MSG09_ROW01, DISP_MSG09_ROW02},
}
Definition at line 23 of file display_task.c.
Referenced by displayMessage().
dispTitle
const char dispTitle[6][11]
Initial value:
                     = {
        {DISP_TITLE01},
        {DISP_TITLE02},
        {DISP_TITLE03},
        {DISP_TITLE04},
        {DISP_TITLE05},
        {DISP_TITLE06},
}
Definition at line 36 of file display_task.c.
Referenced by displayTitle().
setTimeDigitPos
const uint8_t setTimeDigitPos[4]
Initial value:
                              = {
        DIGIT_TEEN_HRS_X,
        DIGIT_UNIT_HRS_X,
        DIGIT_TEEN_MINS_X,
        DIGIT_UNIT_MINS_X,
}
Definition at line 45 of file display_task.c.
Referenced by displayCursorSetTime().