Solari Cifra 5 Firmware: rtc_helpers.c File Reference
rtc_helpers.c File Reference
RTC backup register utilities, Flash settings storage, calibration, and silent period helpers.
#include "rtos_init.h"
#include "rtc_helpers.h"
Functions
uint8_t getMechHours (void)
Read mechanical clock hours from RTC backup register DR0.
uint8_t getMechMinutes (void)
Read mechanical clock minutes from RTC backup register DR1.
static void setMechPosition (uint8_t hours, uint8_t minutes)
Write mechanical clock position to backup registers DR0 and DR1.
void incrementMechMinute (void)
Increment mechanical minute by 1, with hour rollover.
void incrementMechHour (void)
Increment mechanical hour by 1, resetting minutes to 0.
void resetMechPosition (void)
Reset mechanical position to 00:00 in backup registers.
uint8_t getLastTick (void)
Read last tick/tock state from backup register DR2 (bit 0).
void setLastTick (uint8_t tickState)
Write last tick/tock state to backup register DR2 (bit 0).
uint8_t getSilentStartHour (void)
Read silent period start hour from RTC backup register DR3.
uint8_t getSilentEndHour (void)
Read silent period end hour from RTC backup register DR3.
void setSilentHours (uint8_t startHour, uint8_t endHour)
Write silent period hours to backup register DR3.
void getCalibration (uint8_t *plusPulses, uint16_t *calibValue)
Read RTC smooth calibration from backup register DR4.
void setCalibration (uint8_t plusPulses, uint16_t calibValue)
Write RTC smooth calibration to backup register DR4.
void applyCalibration (void)
Apply calibration from backup register to RTC hardware.
void flashWriteSettings (void)
Persist silent hours and calibration to Flash (page 31).
void flashRestoreSettings (void)
Restore settings from Flash to backup registers on battery-loss boot.
uint8_t isInSilentPeriod (void)
Check if current RTC time falls within the silent period.
Variables
RTC_TimeTypeDef RTC_Time
RTC_DateTypeDef RTC_Date
Detailed Description
RTC backup register utilities, Flash settings storage, calibration, and silent period helpers.
Version
2.0
Date
12/02/2026
Author
Alfredo Cortellini
Copyright
Copyright (c) 2026 Alfredo Cortellini. Licensed under CC BY-NC-SA 4.0. See https://creativecommons.org/licenses/by-nc-sa/4.0/
Definition in file rtc_helpers.c.
Function Documentation
getMechHours()
uint8_t getMechHours (void)
Read mechanical clock hours from RTC backup register DR0.
    The mechanical clock position is tracked in backup registers so it
    survives power cycles. Returns 0 if the stored value is out of
    range (> 23), which happens on first battery insertion.
Returns
Mechanical hours (0-23)
Definition at line 39 of file rtc_helpers.c.
References hrtcHandle, and RTC_BKP_MECH_HOURS.
Referenced by clockTask(), incrementMechHour(), incrementMechMinute(), and syncHours().
getMechMinutes()
uint8_t getMechMinutes (void)
Read mechanical clock minutes from RTC backup register DR1.
    Returns 0 if the stored value is out of range (> 59).
Returns
Mechanical minutes (0-59)
Definition at line 51 of file rtc_helpers.c.
References hrtcHandle, and RTC_BKP_MECH_MINUTES.
Referenced by advanceToHourBoundary(), clockTask(), and incrementMechMinute().
setMechPosition()
void setMechPosition (uint8_t hours, uint8_t minutes) static
Write mechanical clock position to backup registers DR0 and DR1.
Parameters
hours Hour value to store (0-23)
minutes Minute value to store (0-59)
Definition at line 62 of file rtc_helpers.c.
References hrtcHandle, RTC_BKP_MECH_HOURS, and RTC_BKP_MECH_MINUTES.
Referenced by incrementMechHour(), incrementMechMinute(), and resetMechPosition().
incrementMechMinute()
void incrementMechMinute (void)
Increment mechanical minute by 1, with hour rollover.
    Called after each coil pulse advances the minute flap.
    Handles 59→00 minute rollover and 23→00 hour rollover.
Definition at line 74 of file rtc_helpers.c.
References getMechHours(), getMechMinutes(), and setMechPosition().
Referenced by clockAdvMinute().
incrementMechHour()
void incrementMechHour (void)
Increment mechanical hour by 1, resetting minutes to 0.
    Called after each servo actuation advances the hour flap.
    Handles 23→00 rollover. Minutes are set to 0 because the
    servo always advances from an hour boundary (XX:00).
Definition at line 97 of file rtc_helpers.c.
References getMechHours(), and setMechPosition().
Referenced by clockAdvHour().
resetMechPosition()
void resetMechPosition (void)
Reset mechanical position to 00:00 in backup registers.
    Called at startup to force a sensor-based search, and when
    mechanical drift is detected during normal operation.
Definition at line 113 of file rtc_helpers.c.
References setMechPosition().
Referenced by clockTask(), createRTOS_Tasks(), and searchForZeroPosition().
getLastTick()
uint8_t getLastTick (void)
Read last tick/tock state from backup register DR2 (bit 0).
    The mechanical clock coil alternates between two pins (tick/tock)
    on each minute advance. This state must persist across power cycles
    to keep the alternation in sync with the mechanical mechanism.
Returns
0 = last was tick (next should be tock), 1 = last was tock
Definition at line 126 of file rtc_helpers.c.
References hrtcHandle, RTC_BKP_FLAG_LAST_TICK, and RTC_BKP_FLAGS.
Referenced by clockAdvMinute().
setLastTick()
void setLastTick (uint8_t tickState)
Write last tick/tock state to backup register DR2 (bit 0).
    Uses read-modify-write to preserve other flag bits in DR2.
Parameters
tickState 0 = tick, 1 = tock
Definition at line 138 of file rtc_helpers.c.
References hrtcHandle, RTC_BKP_FLAG_LAST_TICK, and RTC_BKP_FLAGS.
Referenced by clockAdvMinute().
getSilentStartHour()
uint8_t getSilentStartHour (void)
Read silent period start hour from RTC backup register DR3.
    DR3 packs two hours: start in bits [7:0], end in bits [15:8].
    Returns SILENT_DEFAULT_START (22) if the stored value is out of
    range (> 23).
Returns
Start hour (0-23)
Definition at line 159 of file rtc_helpers.c.
References hrtcHandle, RTC_BKP_SILENT, and SILENT_DEFAULT_START.
Referenced by enterSetSilent(), flashWriteSettings(), and isInSilentPeriod().
getSilentEndHour()
uint8_t getSilentEndHour (void)
Read silent period end hour from RTC backup register DR3.
    Extracts bits [15:8] from DR3. Returns SILENT_DEFAULT_END (9)
    if the stored value is out of range (> 23).
Returns
End hour (0-23)
Definition at line 173 of file rtc_helpers.c.
References hrtcHandle, RTC_BKP_SILENT, and SILENT_DEFAULT_END.
Referenced by enterSetSilent(), flashWriteSettings(), and isInSilentPeriod().
setSilentHours()
void setSilentHours (uint8_t startHour, uint8_t endHour)
Write silent period hours to backup register DR3.
    Packs start in bits [7:0] and end in bits [15:8] of a single
    32-bit register.
Parameters
startHour Hour when silent period begins (0-23)
endHour Hour when silent period ends (0-23)
Definition at line 188 of file rtc_helpers.c.
References hrtcHandle, and RTC_BKP_SILENT.
Referenced by flashRestoreSettings(), and handleSetSilentBtns().
getCalibration()
void getCalibration (uint8_t * plusPulses, uint16_t * calibValue)
Read RTC smooth calibration from backup register DR4.
    DR4 encoding: bit 9 = plus pulses flag, bits [8:0] = calibration
    value (0-511). If the raw register exceeds 0x3FF (invalid), both
    outputs default to 0 (no correction applied).
    The STM32 RTC smooth calibration adds or removes clock pulses
    every 32-second window to fine-tune the RTC oscillator.
Parameters
[out] plusPulses 1 = add pulses (speed up), 0 = remove pulses (slow down)
[out] calibValue Number of pulses to add/remove per 32s (0-511)
Definition at line 206 of file rtc_helpers.c.
References hrtcHandle, and RTC_BKP_CALIB.
Referenced by applyCalibration(), enterSetCorrection(), and flashWriteSettings().
setCalibration()
void setCalibration (uint8_t plusPulses, uint16_t calibValue)
Write RTC smooth calibration to backup register DR4.
    Encodes plusPulses flag in bit 9 and value in bits [8:0].
    Call applyCalibration() afterwards to activate the new value.
Parameters
plusPulses 1 = add pulses (speed up), 0 = remove pulses (slow down)
calibValue Number of pulses per 32s window (0-511)
Definition at line 226 of file rtc_helpers.c.
References hrtcHandle, and RTC_BKP_CALIB.
Referenced by flashRestoreSettings(), and handleSetCorrBtns().
applyCalibration()
void applyCalibration (void)
Apply calibration from backup register to RTC hardware.
    Reads calibration from DR4 and calls HAL_RTCEx_SetSmoothCalib()
    to program the RTC's smooth calibration registers. Called at
    startup and after the user changes calibration from the sub-menu.
    HAL_RTCEx_SetSmoothCalib(hrtc, period, plusPulses, value):
    - period: RTC_SMOOTHCALIB_PERIOD_32SEC (correction window)
    - plusPulses: PLUSPULSES_SET adds (512-value) pulses per window,
      PLUSPULSES_RESET subtracts value pulses per window
    - value: 0-511 pulses to add/remove
Definition at line 245 of file rtc_helpers.c.
References getCalibration(), and hrtcHandle.
Referenced by createRTOS_Tasks(), and handleSetCorrBtns().
flashWriteSettings()
void flashWriteSettings (void)
Persist silent hours and calibration to Flash (page 31).
    Reads current settings from backup registers and writes them as
    a single 64-bit double-word to the last Flash page (0x0800F800).
    Data layout:
      word0 [31:0]:  silentStart[7:0] | silentEnd[15:8] | calibRaw[31:16]
      word1 [63:32]: magic number 0xC1F5A001 (validates data on read)
    STM32G0 Flash notes:
    - Erase unit is one page (2 KB). The full page is erased each time.
    - Program unit is one double-word (64 bits, 8 bytes).
    - Flash endurance is ~10,000 erase cycles (fine for rare settings changes).
    - HAL_FLASH_Unlock/Lock: the Flash control register is write-protected
      by default; Unlock removes protection, Lock restores it.
    RTOS: taskENTER_CRITICAL() disables interrupts during the Flash
    operation (~40ms erase). On single-bank STM32G0 the CPU stalls on
    Flash reads during erase anyway, so this is mainly defensive.
Definition at line 284 of file rtc_helpers.c.
References FLASH_SETTINGS_ADDR, FLASH_SETTINGS_MAGIC, FLASH_SETTINGS_PAGE, getCalibration(), getSilentEndHour(), and getSilentStartHour().
Referenced by handleSetCorrBtns(), and handleSetSilentBtns().
flashRestoreSettings()
void flashRestoreSettings (void)
Restore settings from Flash to backup registers on battery-loss boot.
    Called from createRTOS_Tasks() when ICSR.INITS == 0 (RTC lost power).
    Reads the double-word at FLASH_SETTINGS_ADDR, validates the magic
    number, and writes silent hours and calibration to backup registers.
    If the magic doesn't match (Flash never written = fresh device),
    writes factory defaults to the backup registers.
    Called before the scheduler starts, so no critical section needed.
Definition at line 328 of file rtc_helpers.c.
References FLASH_SETTINGS_ADDR, FLASH_SETTINGS_MAGIC, setCalibration(), setSilentHours(), SILENT_DEFAULT_END, and SILENT_DEFAULT_START.
Referenced by createRTOS_Tasks().
isInSilentPeriod()
uint8_t isInSilentPeriod (void)
Check if current RTC time falls within the silent period.
    Silent period is defined by start/end hours in backup register DR3.
    The check triggers at HH:01 (not HH:00), so the clock can tick to
    the exact start hour before going silent.
    Handles wrap-around midnight (e.g. 22:01→09:00) and same-day
    ranges (e.g. 02:01→05:00).
    STM32 RTC note: HAL_RTC_GetTime() MUST be followed by
    HAL_RTC_GetDate() — the date read unlocks the time shadow registers.
    Skipping GetDate causes GetTime to return stale values.
Returns
1 if currently in silent period, 0 otherwise
Definition at line 376 of file rtc_helpers.c.
References getSilentEndHour(), getSilentStartHour(), hrtcHandle, RTC_Date, and RTC_Time.
Referenced by clockTask(), and handleClockBtns().
Variable Documentation
RTC_Time
RTC_TimeTypeDef RTC_Time
Definition at line 20 of file rtc_helpers.c.
Referenced by clockTask(), displayUpdateTimeVar(), handleSetRtcBtns(), and isInSilentPeriod().
RTC_Date
RTC_DateTypeDef RTC_Date
Definition at line 21 of file rtc_helpers.c.
Referenced by clockTask(), handleSetRtcBtns(), and isInSilentPeriod().