Solari Cifra 5 Firmware: ssd1306.h File Reference
ssd1306.h File Reference
SSD1306 OLED display driver over I2C with scalable font rendering.
#include "main.h"
Macros
#define SSD1306_I2C_ADDR 0x3C << 1
#define SSD1306_I2C_TIMEOUT 10
#define SSD1306_I2C_CMD 0x00
#define SSD1306_I2C_DATA 0x40
#define SSD1306_WIDTH 128
#define SSD1306_HEIGHT 64
#define SSD1306_INIT_LEN 20
#define SSD1306_CHAR_WIDTH 6
Functions
void ssd1306_Init (I2C_HandleTypeDef *hi2c)
void ssd1306_ClearScreen (void)
void ssd1306_WriteChar (char ch, uint8_t fsize)
void ssd1306_WriteString (char *msg, uint8_t fsize)
void ssd1306_SetCursor (uint8_t xpos, uint8_t ypos)
void ssd1306_SetContrast (uint8_t contrast)
void ssd1306_SetDisplayOnOff (uint8_t onOff)
Detailed Description
SSD1306 OLED display driver over I2C with scalable font rendering.
Version
2.0
Date
12/02/2026
Author
Stefan Wagner (original, 2020)
Alfredo Cortellini (STM32 adaptation + font magnification, 2021)
Copyright
Original work Copyright (c) 2020 Stefan Wagner. Licensed under CC BY-SA 3.0. See https://creativecommons.org/licenses/by-sa/3.0/ Project: https://github.com/wagiminator/ATtiny13-TinyOLEDdemo
Modifications Copyright (c) 2026 Alfredo Cortellini. Licensed under CC BY-NC-SA 4.0. See https://creativecommons.org/licenses/by-nc-sa/4.0/
Definition in file ssd1306.h.
Macro Definition Documentation
SSD1306_I2C_ADDR
#define SSD1306_I2C_ADDR 0x3C << 1
Definition at line 27 of file ssd1306.h.
Referenced by i2cWrite().
SSD1306_I2C_TIMEOUT
#define SSD1306_I2C_TIMEOUT 10
Definition at line 28 of file ssd1306.h.
Referenced by i2cWrite().
SSD1306_I2C_CMD
#define SSD1306_I2C_CMD 0x00
Definition at line 29 of file ssd1306.h.
Referenced by ssd1306_Init(), ssd1306_SetContrast(), ssd1306_SetCursor(), and ssd1306_SetDisplayOnOff().
SSD1306_I2C_DATA
#define SSD1306_I2C_DATA 0x40
Definition at line 30 of file ssd1306.h.
Referenced by ssd1306_ClearScreen(), and ssd1306_WriteChar().
SSD1306_WIDTH
#define SSD1306_WIDTH 128
Definition at line 33 of file ssd1306.h.
Referenced by displayMessage(), displayTitle(), and ssd1306_ClearScreen().
SSD1306_HEIGHT
#define SSD1306_HEIGHT 64
Definition at line 34 of file ssd1306.h.
Referenced by ssd1306_ClearScreen().
SSD1306_INIT_LEN
#define SSD1306_INIT_LEN 20
Definition at line 37 of file ssd1306.h.
Referenced by ssd1306_Init().
SSD1306_CHAR_WIDTH
#define SSD1306_CHAR_WIDTH 6
Definition at line 40 of file ssd1306.h.
Referenced by displayMessage(), displayTitle(), and ssd1306_WriteChar().
Function Documentation
ssd1306_Init()
void ssd1306_Init (I2C_HandleTypeDef * hi2c)
Definition at line 132 of file ssd1306.c.
References i2cBuff, i2cHandle, i2cWrite(), ssd1306_ClearScreen(), SSD1306_I2C_CMD, SSD1306_INIT_LEN, and ssd1306_SetDisplayOnOff().
ssd1306_ClearScreen()
void ssd1306_ClearScreen (void)
Definition at line 144 of file ssd1306.c.
References i2cBuff, i2cWrite(), SSD1306_HEIGHT, SSD1306_I2C_DATA, ssd1306_SetCursor(), and SSD1306_WIDTH.
Referenced by displayTask(), enterSetCorrection(), enterSetRtc(), enterSetSilent(), handleSetCorrBtns(), handleSetSilentBtns(), and ssd1306_Init().
ssd1306_WriteChar()
void ssd1306_WriteChar (char ch, uint8_t fsize)
Definition at line 158 of file ssd1306.c.
References col, font_5x8, i2cBuff, i2cWrite(), page, SSD1306_CHAR_WIDTH, SSD1306_I2C_DATA, and ssd1306_SetCursor().
Referenced by displayCursorSetTime(), displayMessage(), displayShowCalibration(), displayShowClock(), displayShowSilentHours(), and ssd1306_WriteString().
ssd1306_WriteString()
void ssd1306_WriteString (char * msg, uint8_t fsize)
Definition at line 196 of file ssd1306.c.
References ssd1306_WriteChar().
Referenced by displayMessage(), and displayTitle().
ssd1306_SetCursor()
void ssd1306_SetCursor (uint8_t xpos, uint8_t ypos)
Definition at line 205 of file ssd1306.c.
References col, i2cBuff, i2cWrite(), page, and SSD1306_I2C_CMD.
Referenced by displayCursorSetTime(), displayMessage(), displayShowCalibration(), displayShowClock(), displayShowSilentHours(), displayTitle(), ssd1306_ClearScreen(), and ssd1306_WriteChar().
ssd1306_SetContrast()
void ssd1306_SetContrast (uint8_t contrast)
Definition at line 220 of file ssd1306.c.
References i2cBuff, i2cWrite(), and SSD1306_I2C_CMD.
ssd1306_SetDisplayOnOff()
void ssd1306_SetDisplayOnOff (uint8_t onOff)
Definition at line 228 of file ssd1306.c.
References i2cBuff, i2cWrite(), and SSD1306_I2C_CMD.
Referenced by displayOnOff(), and ssd1306_Init().