Solari Cifra 5 Firmware: ssd1306.c File Reference
ssd1306.c File Reference
SSD1306 OLED display driver over I2C with scalable font rendering.
#include "ssd1306.h"
Functions
static void i2cWrite (uint8_t mode, uint8_t *data, uint8_t lenght)
void ssd1306_Init (I2C_HandleTypeDef *hi2c)
void ssd1306_ClearScreen (void)
void ssd1306_WriteChar (char ch, uint8_t fsize)
void ssd1306_WriteString (char *msg, uint8_t fsize)
void ssd1306_SetCursor (uint8_t xpos, uint8_t ypos)
void ssd1306_SetContrast (uint8_t contrast)
void ssd1306_SetDisplayOnOff (uint8_t onOff)
Variables
const uint8_t font_5x8 []
static uint8_t col
static uint8_t page
static I2C_HandleTypeDef * i2cHandle = NULL
static uint8_t i2cBuff [24]
Detailed Description
SSD1306 OLED display driver over I2C with scalable font rendering.
Version
2.0
Date
12/02/2026
Author
Stefan Wagner (original, 2020)
Alfredo Cortellini (STM32 adaptation + font magnification, 2021)
Copyright
Original work Copyright (c) 2020 Stefan Wagner. Licensed under CC BY-SA 3.0. See https://creativecommons.org/licenses/by-sa/3.0/ Project: https://github.com/wagiminator/ATtiny13-TinyOLEDdemo
Modifications Copyright (c) 2026 Alfredo Cortellini. Licensed under CC BY-NC-SA 4.0. See https://creativecommons.org/licenses/by-nc-sa/4.0/
Definition in file ssd1306.c.
Function Documentation
i2cWrite()
void i2cWrite (uint8_t mode, uint8_t * data, uint8_t lenght) static
Definition at line 124 of file ssd1306.c.
References Error_Handler(), i2cHandle, SSD1306_I2C_ADDR, and SSD1306_I2C_TIMEOUT.
Referenced by ssd1306_ClearScreen(), ssd1306_Init(), ssd1306_SetContrast(), ssd1306_SetCursor(), ssd1306_SetDisplayOnOff(), and ssd1306_WriteChar().
ssd1306_Init()
void ssd1306_Init (I2C_HandleTypeDef * hi2c)
Definition at line 132 of file ssd1306.c.
References i2cBuff, i2cHandle, i2cWrite(), ssd1306_ClearScreen(), SSD1306_I2C_CMD, SSD1306_INIT_LEN, and ssd1306_SetDisplayOnOff().
ssd1306_ClearScreen()
void ssd1306_ClearScreen (void)
Definition at line 144 of file ssd1306.c.
References i2cBuff, i2cWrite(), SSD1306_HEIGHT, SSD1306_I2C_DATA, ssd1306_SetCursor(), and SSD1306_WIDTH.
Referenced by displayTask(), enterSetCorrection(), enterSetRtc(), enterSetSilent(), handleSetCorrBtns(), handleSetSilentBtns(), and ssd1306_Init().
ssd1306_WriteChar()
void ssd1306_WriteChar (char ch, uint8_t fsize)
Definition at line 158 of file ssd1306.c.
References col, font_5x8, i2cBuff, i2cWrite(), page, SSD1306_CHAR_WIDTH, SSD1306_I2C_DATA, and ssd1306_SetCursor().
Referenced by displayCursorSetTime(), displayMessage(), displayShowCalibration(), displayShowClock(), displayShowSilentHours(), and ssd1306_WriteString().
ssd1306_WriteString()
void ssd1306_WriteString (char * msg, uint8_t fsize)
Definition at line 196 of file ssd1306.c.
References ssd1306_WriteChar().
Referenced by displayMessage(), and displayTitle().
ssd1306_SetCursor()
void ssd1306_SetCursor (uint8_t xpos, uint8_t ypos)
Definition at line 205 of file ssd1306.c.
References col, i2cBuff, i2cWrite(), page, and SSD1306_I2C_CMD.
Referenced by displayCursorSetTime(), displayMessage(), displayShowCalibration(), displayShowClock(), displayShowSilentHours(), displayTitle(), ssd1306_ClearScreen(), and ssd1306_WriteChar().
ssd1306_SetContrast()
void ssd1306_SetContrast (uint8_t contrast)
Definition at line 220 of file ssd1306.c.
References i2cBuff, i2cWrite(), and SSD1306_I2C_CMD.
ssd1306_SetDisplayOnOff()
void ssd1306_SetDisplayOnOff (uint8_t onOff)
Definition at line 228 of file ssd1306.c.
References i2cBuff, i2cWrite(), and SSD1306_I2C_CMD.
Referenced by displayOnOff(), and ssd1306_Init().
Variable Documentation
font_5x8
const uint8_t font_5x8[]
Definition at line 24 of file ssd1306.c.
Referenced by ssd1306_WriteChar().
col
uint8_t col static
Definition at line 97 of file ssd1306.c.
Referenced by ssd1306_SetCursor(), and ssd1306_WriteChar().
page
uint8_t page static
Definition at line 97 of file ssd1306.c.
Referenced by ssd1306_SetCursor(), and ssd1306_WriteChar().
i2cHandle
I2C_HandleTypeDef* i2cHandle = NULL static
Definition at line 100 of file ssd1306.c.
Referenced by i2cWrite(), and ssd1306_Init().
i2cBuff
uint8_t i2cBuff[24] static
Initial value:
               = {
0xA8, 0x1F,
0x22, 0x00, 0x03,
0xDA, 0x02,
0x20, 0x00,
0x8D, 0x14,
0x81, 0xFF,
0xD5, 0xF0,
0x2E,
0xD3, 0x00,
0xA1, 0xC8,
0x00, 0x00,
0x00, 0x00,
}
Definition at line 101 of file ssd1306.c.
Referenced by ssd1306_ClearScreen(), ssd1306_Init(), ssd1306_SetContrast(), ssd1306_SetCursor(), ssd1306_SetDisplayOnOff(), and ssd1306_WriteChar().